# netlify.toml

[build]
  # The command to build your Next.js application.
  # This script (defined in package.json) will run 'next build && next export'.
  command = "npm run build"

  # The directory where Next.js's 'next export' command outputs the static files.
  # By default, 'next export' creates a folder named 'out'.
  publish = "out"

  # Specify the Node.js version for Netlify's build environment.
  # This helps ensure consistency with your local development environment
  # and the version specified in stackbit.config.ts (nodeVersion: '18').
[build.environment]
  NODE_VERSION = "18"

# Configuration for the Netlify Visual Editor plugin.
# This plugin integrates Stackbit's visual editing capabilities with your site.
[[plugins]]
  package = "@netlify/plugin-visual-editor"

# Essential redirect rule for the Netlify Visual Editor to function correctly,
# especially during local development (`netlify dev`).
# It proxies requests from Netlify's internal dev URL to the Stackbit dev server
# running on localhost:8288.
[[redirects]]
  from = "/.ntlfy-dev/*"
  to = "http://localhost:8288/:splat"
  status = 200
  headers = {X-NF-Hidden-Proxy = "true"}

# You can add other Netlify configurations here if needed, for example:
#
# [[headers]]
#   for = "/*"
#     [headers.values]
#       X-Frame-Options = "DENY"
#       X-Content-Type-Options = "nosniff"
#       X-XSS-Protection = "1; mode=block"
#       Referrer-Policy = "no-referrer-when-downgrade"
#
# [[headers]]
#   for = "/images/*"
#     [headers.values]
#       Cache-Control = "public, max-age=31536000" # Cache images for a year

[build]
  command = "npm run build"
  publish = "out" # Ensure this matches your output directory

[build.environment]
  NODE_VERSION = "20"